### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by binxiangni** [rcppsmc/rcppsmc#27]
When I am trying to build the package in the Rstudio on macOS, installation failed. The error message is:
```
/usr/local/clang4/bin/clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/include -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2  -c LinReg.cpp -o LinReg.o
In file included from LinReg.cpp:23:
In file included from ../inst/include/LinReg.h:23:
In file included from ../inst/include/smctc.h:96:
In file included from /usr/local/clang4/bin/../include/c++/v1/cmath:305:
/usr/local/clang4/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>
              ^~~~~~~~
```
It seems that the header file cannot be found. Any hint to fix it?

**Comment by adamjohansen** [comment]
I don't have a mac to hand, or clang installed on this box. But a few thoughts:

What version of clang are you using? There have been a few issues with standard headers in the past (cf. https://bugs.launchpad.net/ubuntu/+source/llvm-defaults/+bug/1242300).

Does a simple hello world c++ program making use of cstdio build in your environment?

Are your R Makevars pointing to the right headers?

**Comment by eddelbuettel** [comment]
@coatless, can you help?

_Most often_ this is a mismatch between your system compiler and the compiler R uses.  The excellent hardware from Cupertino seems to get coupled with less and less useful software ...

In the meantime, please try a lab computer running Linux, or a VM, or set your Mac up in a way the CRAN computers are set up as RcppSMC passes there.

**Comment by coatless** [comment]
@binxiangni you recently upgraded to High Sierra eh? 

Open terminal and re-run:

```
xcode-select --install
```

https://twitter.com/axiomsofxyz/status/913634156130824192

**Comment by binxiangni** [comment]
It works. Thanks for all of your help. 😀
