### ISSUE TITLE
Install and building error

### ISSUE THREAD

**Issue by covaruber** [rcppsmc/rcppsmc#46]
This seems to be similar to installation issue #27 but solutions there haven't provided a solution in my case.

When I tried to build my R package I first got a message "unsupported option '-fopenmp'" which in the past when I was using mac-Sierra it was fixed by changing the ~/.R/Makevars file as suggested in https://github.com/velocyto-team/velocyto.R/issues/2. When moved to Mojave I had the same -fopenmp issue so I thought the solution would be the same, but this time after changing my  ~/.R/Makevars file I got a new error message is:

```
/usr/local/clang4/bin/clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp  -fPIC  -Wall -g -O2 -c MNR.cpp -o MNR.o
In file included from MNR.cpp:5:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp/r/headers.h:59:
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /usr/local/clang4/bin/../include/c++/v1/cmath:305:
**/usr/local/clang4/bin/../include/c++/v1/math.h:301:15: fatal error: 'math.h' file not found
#include_next <math.h>**
              ^~~~~~~~
1 error generated.
make: *** [MNR.o] Error 1
```

It seems that the math.h file cannot be found. Any hint to fix it?

My ~/.R/Makevars file looks like this and clang is in such directory

```
CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
CXX14=/usr/local/clang4/bin/clang++
CXX17=/usr/local/clang4/bin/clang++
CXX1X=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib
```

I have installed the newest Xcode version as suggested in #27 :

```
Xcode 10.1
Build version 10B61
```

My clang version:

```
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Could someone give me a hint how to fix it?

**Comment by eddelbuettel** [comment]
I don't think this is a bug in RcppSMC but rather a shortcoming in your setup of your macOS machine.  I would suggest you get in touch in with the r-sig-mac mailing list, or follow posts by good folks like @coatless who tirelessly try to put structure into this somewhat unstructured territory.

I am inclined to close this -- as [CRAN shows the package builds fine everywhere](https://cloud.r-project.org/web/checks/check_results_RcppSMC.html).  Ok?

**Comment by eddelbuettel** [comment]
As I said, I suggest you go to the r-sig-mac list.  

As I demonstrated, the package I mainrtain is flawless at CRAN including on two macOS setups.

I am truly sorry for the trouble you have. I can recommend Linux as a computing environment.
