### ISSUE TITLE
Add RcppSMC to r-universe ?

### ISSUE THREAD

**Issue by eddelbuettel** [rcppsmc/rcppsmc#66]
I mentioned in passing that RcppSMC is now bing built by Jeroen's r-universe.dev.  (Some of the technical/philosophical question notwithstanding ....) it occurred to me that we may actually benefit from joining as an org because we could then get things like the example packages autobuilt even when they are not (yet ?) on CRAN.  

Yay? Nay? Maybe?

**Comment by adamjohansen** [comment]
I have no experience with r-universe, but it doesn't seem like a bad idea. I'd be happy to defer to your judgement on this one, personally.

**Comment by eddelbuettel** [comment]
I have some reservations about it, but it does not hurt.  Adds an additional CI layer and binaries upon each commit.  It already does it for our main package (via my handle), we could expand to the org and other (GitHub only?) packages (not requiring my handle once we set the org up).  

(Also:  0.2.5 upload was successful and took out the build failure on Solaris I mised prior to 0.2.4.)

**Comment by LeahPrice** [comment]
I don't know much about r-universe but if you think it's a good idea @eddelbuettel then I'm happy for it too.

**Comment by eddelbuettel** [comment]
No urgency.  Also not obvious to find good examples.  Here maybe one:  https://r4epi.r-universe.dev/ui#builds   Two packages. one listed maintainer.   It would allow us package builds of, say, example packages before we get them to CRAN and/or dev versions of things at CRAN.  (I.e. we had RcppSMC build between 0.2.3 and the recent (large) upload of 0.2.4).

**Comment by ilyaZar** [comment]
Hi. Sounds like a reasonable thing!

What do I have to do on my side regarding the `SVmodelRcppSMC` example package linked under our org? I skimmed through 
https://ropensci.org/blog/2021/03/04/r-universe-buildsystem/ but it's quite high level and assumes a bit of familiarity, I guess, with the topic of build systems and CI . Which I don't have ... (maybe you have some resources on this @eddelbuettel ?).

Seems like a reasonable time investment to learn about though, which pays off later via automating manual build tasks, but that's all I've (hopefully) understood about it so far....

**Comment by eddelbuettel** [comment]
There are two steps.  As I recall, one is to install Jeroen's universe application inside our org.  That IIRC starts some scanning.  I am a little fuzzy on what else it does.  The second, more finegrained, is a repo 'universe' inside our org with a file `packages.json` where one can turn on and off which ones one wants.  All this apparently also allows for one-to-many mappings so just how RcppSMC is currently in universe, it could be in yours and it could be in one for RcppSMC if we set that up.

What does it do?  CI build from source, as well as windows and macOS binaries. Not the most important thing in the world, but helpful.  What I find to be somewhere between irritating and dangerous is that they are not labelled.  We could add one hundred to commits to our repo, leave DESCRIPTION at 0.2.5 and he would build 0.2.5 binaries. And we have no way to if a potential user got those from him, or CRAN.   Another reason why I keep up with my 20+ year old habit of sub-revisions between CRAN relases (i.e 0.2.5.1).  But maybe that is just because I am a stickler ...

**Comment by ilyaZar** [comment]
Ok I better understand the general issue now. Its not ideal that releases/binaries are not labelled but this architecture/technical argument aside, having CI for the other org packages sounds like a good thing.

I think (from my limited perspective) that most users get the package from CRAN, a little more experienced users directly from GitHub and some from the universe-thing.

The latter type of users probably recall where they got the package from... and should also be aware of the fact that they are installing binaries from sort of "random commit snapshots/demo/dev package releases" or whatever one likes to call that. And that this really is all a bit of experimental (plus reverting back to the older CRAN version is always possible).

So I'd be happy to try this if you also have a good feeling!

**Comment by adamjohansen** [comment]
On balance it sounds to me like we'd gain more than we lose, and in the absence of perfection better than the current state of affairs is enough. But we should probably try to remember to increment the subminor version number whenever committing anything to the main branch.

**Comment by eddelbuettel** [comment]
That sums up my ambivalence too :)  So I guess next step is to look into setting the 'universe' app up.

**Comment by eddelbuettel** [comment]
I think it was already building anyway as it was include via [my universe's `package.json`](https://github.com/eddelbuettel/universe/blob/master/packages.json) but with github 'app' installed I think we get slightly better feedback from runs.  

So closing as completed.
