### ISSUE TITLE
Quick 0.2.6 release ?

### ISSUE THREAD

**Issue by eddelbuettel** [rcppsmc/rcppsmc#70]
My own backtest keep hitting the g++-11 issue we already fixed, and I convinced CRAN to run a wider test.

With that, any objections to rolling a (otherwise fairly simple) quick 0.2.6 release ?

**Comment by adamjohansen** [comment]
Not from me.

**Comment by ilyaZar** [comment]
Neither from me, thanks @eddelbuettel !

**Comment by LeahPrice** [comment]
Nor from me. Thank you @eddelbuettel! Enjoy the holiday period everyone.

**Comment by eddelbuettel** [comment]
And all taken care of.  I had missed one final `\url{}` to `\doi{}` change that `R CMD check` under r-devel wanted.  This is now in the repo but it 'technically' came after the merge in #71.  Not that anybody cares...
