### ISSUE TITLE
CRAN notice on uninitialized variable

### ISSUE THREAD

**Issue by eddelbuettel** [rcppsmc/rcppsmc#74]
Incoming email by Brian Ripley says

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_RcppSMC.html>.
> 
> It has always been the intention to report
> -Winitialized warnings, but the format had changed.
> clang (LLVM and Apple) reports many more than gcc.
> 
> Please correct before 2023-04-04 to safely retain your package on CRAN.

which gets us to [CRAN results for RcppSMC](https://cran.r-project.org/web/checks/check_results_RcppSMC.html) which currently has for his Fedora machine with `clang++-16`:

> Version: 0.2.6
> Check: whether package can be installed
> Result: WARN
>    Found the following significant warnings:
>     ../inst/include/history.h:70:75: warning: field 'number' is uninitialized when used here [-Wuninitialized]
>    See ‘/data/gannet/ripley/R/packages/tests-clang/RcppSMC.Rcheck/00install.out’ for details.
>    * used C++ compiler: ‘clang version 16.0.0’
> Flavor: r-devel-linux-x86_64-fedora-clang

but it turns out that a very simple change takes care of it (in the 'tests still pass' sense) _and_ makes the warning go aways (though I used `clang++-15` here; he noted the different output format):

```diff
modified   inst/include/history.h
@@ -63,9 +63,9 @@ namespace smc {
     template <class Space>class historyelement
     {
     private:
-        long number; //!< The number of particles (presently redundant as this is not a function of iteration)
-        int nAccepted; //!< Number of MCMC moves accepted during this iteration.
-        int nRepeat; //!< Number of MCMC iterations performed at this iteration (per particle)
+        long number = 0; //!< The number of particles (presently redundant as this is not a function of iteration)
+        int nAccepted = 0; //!< Number of MCMC moves accepted during this iteration.
+        int nRepeat = 0; //!< Number of MCMC iterations performed at this iteration (per particle)
         population<Space> pop; //!< The particles themselves (values and weights)
         arma::Col<unsigned int> ancestorIndices = arma::Col<unsigned int>(number);
         historyflags flags; //!< Flags associated with this iteration.
```

so I will PR this in a moment.

**Comment by ilyaZar** [comment]
Yes we had a number of uninitialized constants I did not take care of properly back then ... and now the compiler helps us :) next time it will be ChatGPT. Thanks for the catch and the PR @eddelbuettel !

**Comment by adamjohansen** [comment]
Yes, thanks for fixing that. It's fairly uncontroversial. Paranoid compilers sometimes catch apparently harmless issues that have unintended consequences which mere humans don't manage to anticipate.

**Comment by eddelbuettel** [comment]
Thanks for the catch go to the ever-tireless Brian Ripley.  I just do as I am told^Hasked to :grinning:

**Comment by LeahPrice** [comment]
Thanks very much Dirk!

**Comment by eddelbuettel** [comment]
Thanks!  

Looks like we're all good with wrapping this up as a new 0.2.7 for CRAN then (with the other few changes since 0.2.6). I will take care of it.

**Comment by eddelbuettel** [comment]
And that circle is closed now with an auto-processed admission:

> Dear maintainer,
>
> thanks, package RcppSMC_0.2.7.tar.gz is on its way to CRAN.
> 
> Best regards,
> CRAN teams' auto-check service
