### ISSUE TITLE
ORCID IDs

### ISSUE THREAD

**Issue by eddelbuettel** [rcppsmc/rcppsmc#76]
CRAN had long supported a format called 'Authors@R' (described also in a R Journal article years ago) and now requires it.  This helps with proper first and surname, email field -- and support ORCID via a comment field.  (One day this may be a proper field.)

I added mine, but need yours.  So tagging @adamjohansen @LeahPrice @ilyaZar for yours.

Per commit https://github.com/rcppsmc/rcppsmc/commit/316769763d2ca7fe471aa615bcde991e2c787af1 just made we now have https://github.com/rcppsmc/rcppsmc/blob/316769763d2ca7fe471aa615bcde991e2c787af1/DESCRIPTION#L6-L10 and similar comment fields can be added in follow-up commits once we have your ORCIDs.  This is of course fully optional and not mandatory.  Email field is optional too and only required for the one field tagged 'cre' which corresponds to the old 'Maintainer' field.

**Comment by ilyaZar** [comment]
@eddelbuettel thanks for paying attention and updating this , just added a commit with my info

**Comment by adamjohansen** [comment]
Thanks, @eddelbuettel -- I've added mine, too.

**Comment by eddelbuettel** [comment]
Kewl.  As I said, email is commonly omitted for all roles but the (precisely one per the rules) tagged 'cre' aka Maintainer.  But it does no harm.  ORCID should be even better / more unique and may one day be promoted to a proper field (or so I heard, may take a while).

Will ship this to CRAN next time we update.

**Comment by eddelbuettel** [comment]
It does zero harm so no need to remove it.

**Comment by LeahPrice** [comment]
Thanks @eddelbuettel ! I've added mine now too. I included my email for consistency.

**Comment by eddelbuettel** [comment]
Closing this now everybody replied so promptly and we're all set for this.
